language: go
go: '1.10'

env:
- DEP_VERSION="0.4.1"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
- dep ensure -v

script:
  - bash xcross.sh
  - for f in  awscli-windows-*; do mv -v -- "$f" "$f.exe"; done;
  - echo "Generated files"
  - ls -al cli-*

deploy:
  provider: releases
  skip_cleanup: true	
  api_key:
    secure: rLbxgXXwjY8PZAyww0V1tGc+FOaVP15KuMPV/AkornjvDo5Jc4ET+HX5n9bDL2ZpkTtlAs+/pTFkx30BOuOpCK89ijOfLMCGIAjRNMGqMMdSawDO+BgF5FmvuLwfbxOlaMFFFz4bXV+HHJ5LY+hlQ/vzqhEhkOZJpTwtF2sAmpkjhE/NGyDKpZlbECFGxlx3bIn7ak9ScsTqZXnbOu89BoRvFv5PruLTbLyogn8nL4xbcvbB5mVQUVV1aSPubUmDUG4/AFHVgjK5JjFK1NybHHFWsZvAYzCaqPpjlK3a3FzdgP3Jlm3SLgG9ncK03zcS/Fh7fpIOECek5ZhvxqUnyzcfzEJt3HjY+Ux24H6OgQ5l6ytafvdcv2QOA2lhkK2tqjbNGYT7MMCA2rXBYwb0ilHDKLLEfp9qnkQIHq51m8p/8y1DTDnV6ux5naLjIphvHD+FEZV84ytrE/aSWB4PERFiWMiMThRZOHvIiNwXLPVVBc/YhOEs9FXlmRtGeE7gKpOqhjsB5m8iCHlj49e5y0v/gyEBYRoxbiKvllN3qDrDel35+j0Mz1lgPD2x+NLa2+42kR3dys7l7Kwymi5iLjpiktlH8h5aXwcj7vGVIThvjU7excwVskHhzwfXGX4J4wCbTT7jW3SDIN9Nvg9810Pb7TBYY+3zh9oX8R0+1ec=
  file_glob: true
  file:
  - awscli-*
  on:
    repo: nirekin/awscli
    tags: true
